### ISSUE TITLE
Adicionar Google Analytics no projeto

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentorship-backend#46]
- [x] Criar configuração
- [x] Adicionar no projeto
- [x] Configurar no RDstation

**Comment by Nibuitoni** [comment]
Não dá para ir pelo caminho do maping no cloud run, porque está armazenado no southamerica.

![Image](https://user-images.githubusercontent.com/64747795/207301761-5e31eff5-fb2c-4e78-b93f-94f60281cc53.png)

Na documentação do google, temos 3 opções para cadastrar um subdomínio https://cloud.google.com/run/docs/mapping-custom-domains
Os locais disponíveis para o mapeamento são:

![Image](https://user-images.githubusercontent.com/64747795/207302529-a1794207-271c-47b4-a9e7-581b448c8935.png)

**Comment by Nibuitoni** [comment]
Subdomínio configurado, página acessível em: vagas.saibro.tech/job

**Comment by piantino** [comment]
> Subdomínio configurado, página acessível em: vagas.saibro.tech/job

Resolvemos mudar para:
https://junior.saibro.tech/job

@Nibuitoni não tenho acesso ao analytics que criou, faltou me dar permissão.

**Comment by Nibuitoni** [comment]
> > Subdomínio configurado, página acessível em: vagas.saibro.tech/job
> 
> Resolvemos mudar para: https://junior.saibro.tech/job
> 
> @Nibuitoni não tenho acesso ao analytics que criou, faltou me dar permissão.

Olhei as permissões, e você parece estar com permissão: 
![image](https://user-images.githubusercontent.com/64747795/207845974-bcf77c5f-8d0a-4a22-a7d0-593c3253c3df.png)
