### ISSUE TITLE
Criar PDF comercial e apoio

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentorship-backend#80]
Documento que está sendo desenvolvido:
[Proposta](https://docs.google.com/document/d/11Y0d309QEEf3kFAeIBt8hMcJnS84hMxCYgKp9FPVVlw/edit)

**Comment by Nibuitoni** [comment]
Legal, fiz esse ajuste.
[Proposta Comercial Saibro.pdf](https://github.com/saibrotech/mentorship-backend/files/10103035/Proposta.Comercial.Saibro.pdf)

**Comment by piantino** [comment]
> Legal, fiz esse ajuste. [Proposta Comercial Saibro.pdf](https://github.com/saibrotech/mentorship-backend/files/10103035/Proposta.Comercial.Saibro.pdf)

Aprovado, como primeira versão está ótimo.
